### ISSUE TITLE
Is it possible to run Open-Canvas on Linux fully-local using a local LangGraph CLI instead of LangGraph Studio cloud?

### ISSUE THREAD

**Issue by PieBru** [langchain-ai/open-canvas#181]
Said all in the title.
Thank you.

**Comment by dashan1127** [comment]
Brother, help, I used your method to start docker on linux, and an error occurred when starting open-canvas image. I used langsmith's personal key


root@pekpheds01309:/deps/open-canvas# docker logs 60e67404cdd4
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
2024-11-12T00:53:24.371303Z [info     ] Started server process [1]     [uvicorn.error] api_revision=2f1052b api_variant=local color_message=Started server process [%d]
2024-11-12T00:53:24.371498Z [info     ] Waiting for application startup. [uvicorn.error] api_revision=2f1052b api_variant=local
2024-11-12T00:53:24.371831Z [warning  ] No license key found, running in test mode with LangSmith API key. For production use, set LANGGRAPH_CLOUD_LICENSE_KEY in environment. [langgraph_license.validation] api_revision=2f1052b api_variant=local
2024-11-12T00:53:25.553440Z [info     ] HTTP Request: GET https://apigw-beta.test.hihonor.com/api/langsmith/auth?langgraph-api=true "HTTP/1.1 200 " [httpx] api_revision=2f1052b api_variant=local
2024-11-12T00:53:25.611809Z [error    ] Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/api/langgraph_api/lifespan.py", line 29, in lifespan
  File "/usr/local/lib/python3.12/site-packages/langgraph_storage/database.py", line 115, in start_pool
    await migrate()
  File "/usr/local/lib/python3.12/site-packages/langgraph_storage/database.py", line 97, in migrate
    if version <= current_version:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'int' and 'str'
 [uvicorn.error] api_revision=2f1052b api_variant=local
2024-11-12T00:53:25.612057Z [error    ] Application startup failed. Exiting. [uvicorn.error] api_revision=2f1052b api_variant=local

**Comment by lanesky** [comment]
@dashan1127 

It seems that the API revision you’re running is different from mine. The API revision that worked fine in my environment was `4da016a`, while yours is `2f1052b`. I suspect the issue may be related to the base image, specifically `langchain/langgraphjs-api:20`. I also noticed that this image on Docker Hub has been updating frequently, so you might want to try using `langchain/langgraphjs-api:20-4da016a`, which matches the API revision that has been working well in my environment. 

Here is the log from my environment."

```
2024-11-12T05:46:49.017145Z [info     ] Started server process [1]     [uvicorn.error] api_revision=4da016a api_variant=local color_message=Started server process [%d]
2024-11-12T05:46:49.017285Z [info     ] Waiting for application startup. [uvicorn.error] api_revision=4da016a api_variant=local
2024-11-12T05:46:49.017490Z [warning  ] No license key found, running in test mode with LangSmith API key. For production use, set LANGGRAPH_CLOUD_LICENSE_KEY in environment. [langgraph_license.validation] api_revision=4da016a api_variant=local
2024-11-12T05:46:49.336546Z [info     ] HTTP Request: GET https://api.smith.langchain.com/auth?langgraph-api=true "HTTP/1.1 200 OK" [httpx] api_revision=4da016a api_variant=local
2024-11-12T05:46:49.390290Z [info     ] Postgres pool stats            [langgraph_storage.database] api_revision=4da016a api_variant=local connections_ms=30 connections_num=1 pool_available=1 pool_max=150 pool_min=1 pool_size=1 requests_num=1 requests_waiting=0 usage_ms=2
2024-11-12T05:46:49.446827Z [info     ] Started server process [1]     [uvicorn.error] api_revision=4da016a api_variant=local color_message=Started server process [%d]
2024-11-12T05:46:49.446973Z [info     ] Redis pool stats               [langgraph_storage.redis] api_revision=4da016a api_variant=local idle_connections=1 in_use_connections=0 max_connections=500
2024-11-12T05:46:49.447773Z [info     ] Waiting for application startup. [uvicorn.error] api_revision=4da016a api_variant=local

```

**Comment by dashan1127** [comment]
Brother, I have changed it to langchain/langgraphjs-api:20-4da016a and re-mirrored it, but the same error still occurs.


podman start -a open-canvas_langgraph-redis_1
[langgraph-redis]    | 1:C 12 Nov 2024 09:10:38.038 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
[langgraph-redis]    | 1:C 12 Nov 2024 09:10:38.038 # Redis version=6.2.16, bits=64, commit=00000000, modified=0, pid=1, just started
[langgraph-redis]    | 1:C 12 Nov 2024 09:10:38.038 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
[langgraph-redis]    | 1:M 12 Nov 2024 09:10:38.038 * monotonic clock: POSIX clock_gettime
[langgraph-redis]    | 1:M 12 Nov 2024 09:10:38.040 * Running mode=standalone, port=6379.
[langgraph-redis]    | 1:M 12 Nov 2024 09:10:38.040 # Server initialized
[langgraph-redis]    | 1:M 12 Nov 2024 09:10:38.040 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
[langgraph-redis]    | 1:M 12 Nov 2024 09:10:38.040 * Ready to accept connections
podman start -a open-canvas_langgraph-postgres_1
[langgraph-postgres] |
[langgraph-postgres] | PostgreSQL Database directory appears to contain a database; Skipping initialization
[langgraph-postgres] |
2024-11-12 09:10:39.514 UTC [1] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-11-12 09:10:39.515 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-11-12 09:10:39.515 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-11-12 09:10:39.518 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-11-12 09:10:39.524 UTC [27] LOG:  database system was shut down at 2024-11-12 06:42:36 UTC
2024-11-12 09:10:39.577 UTC [1] LOG:  database system is ready to accept connections
podman start -a open-canvas_langgraph-api_1
[langgraph-api]      | 2024-11-12T09:10:42.686398Z [info     ] Started server process [1]     [uvicorn.error] api_revision=4da016a api_variant=local color_message=Started server process [%d]
[langgraph-api]      | 2024-11-12T09:10:42.686620Z [info     ] Waiting for application startup. [uvicorn.error] api_revision=4da016a api_variant=local
[langgraph-api]      | 2024-11-12T09:10:42.687035Z [warning  ] No license key found, running in test mode with LangSmith API key. For production use, set LANGGRAPH_CLOUD_LICENSE_KEY in environment. [langgraph_license.validation] api_revision=4da016a api_variant=local
[langgraph-api]      | 2024-11-12T09:10:44.766037Z [info     ] HTTP Request: GET https://apigw-beta.test.xxx.com/api/langsmith/auth?langgraph-api=true "HTTP/1.1 200 " [httpx] api_revision=4da016a api_variant=local
[langgraph-api]      | 2024-11-12T09:10:44.881219Z [error    ] Traceback (most recent call last):
[langgraph-api]      |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
[langgraph-api]      |     async with self.lifespan_context(app) as maybe_state:
[langgraph-api]      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
[langgraph-api]      |   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
[langgraph-api]      |     return await anext(self.gen)
[langgraph-api]      |            ^^^^^^^^^^^^^^^^^^^^^
[langgraph-api]      |   File "/api/langgraph_api/lifespan.py", line 29, in lifespan
[langgraph-api]      |   File "/usr/local/lib/python3.12/site-packages/langgraph_storage/database.py", line 115, in start_pool
[langgraph-api]      |     await migrate()
[langgraph-api]      |   File "/usr/local/lib/python3.12/site-packages/langgraph_storage/database.py", line 97, in migrate
[langgraph-api]      |     if version <= current_version:
[langgraph-api]      |        ^^^^^^^^^^^^^^^^^^^^^^^^^^
[langgraph-api]      | TypeError: '<=' not supported between instances of 'int' and 'str'
[langgraph-api]      |  [uvicorn.error] api_revision=4da016a api_variant=local
[langgraph-api]      | 2024-11-12T09:10:44.881441Z [error    ] Application startup failed. Exiting. [uvicorn.error] api_revision=4da016a api_variant=local
exit code: 3

**Comment by lanesky** [comment]
Sorry to hear that. What is the "https://apigw-beta.test.xxx.com/api/langsmith/auth?langgraph-api=true" in your log? Is it an api stub?

**Comment by IsraelShok** [comment]
@lanesky 
I did exactly as you did and it looks like the containers are working, the app uploads with "yarn dev", but I got an error about "Thread id is not found".
Are you familiar with this? 
How can I know if the app is connected to the containers? it's the same error with the docker on air and without.

![image](https://github.com/user-attachments/assets/3221ad61-12ff-4087-ab4c-fbf1c3e641fb)


![image](https://github.com/user-attachments/assets/d59b73c0-8d07-47af-bc9b-515713d39574)

**Comment by dashan1127** [comment]
The container is deployed in the company's intranet. Accessing langchain requires a proxy. This address is accessible to the Auth authentication interface. What a strange problem. Brother, is there any other way? Please help.

**Comment by lanesky** [comment]
I have reviewed the related source code (you can also access it by dumping `storage\langgraph_storage\database.py` from the container). The error seems to occur because the return value of the SQL statement `SELECT version FROM schema_migrations ORDER BY version DESC LIMIT 1` was a string, whereas an integer was expected. Please check the `schema_migrations` table in your PostgreSQL database to ensure it has the correct schema, specifically that the version column is of type `bigint`. If the schema is correct, the issue may lie between the psycopg PostgreSQL driver and your database. You can also check the data records in the `schema_migrations` table to get a clue as to why a string was returned when executing that SQL statement.

```py
async def migrate() -> None:
    async with connect() as conn, conn.cursor() as cur:
        try:
            results = await cur.execute(
                "select version from schema_migrations order by version desc limit 1",
                prepare=False,
            )
            current_version = (await results.fetchone())["version"]
        except UndefinedTable:
            await cur.execute(
                """
                CREATE TABLE schema_migrations (
                    version bigint primary key,
                    dirty boolean not null
                )
                """,
                prepare=False,
            )
            current_version = -1
        for migration_path in sorted(os.listdir(config.MIGRATIONS_PATH)):
            version = int(migration_path.split("_")[0])
            if version <= current_version:
                continue
            with open(os.path.join(config.MIGRATIONS_PATH, migration_path)) as f:
                await cur.execute(f.read(), prepare=False)
            await cur.execute(
                "INSERT INTO schema_migrations (version, dirty) VALUES (%s, %s)",
                (version, False),
            )
            await logger.ainfo("Applied database migration", version=version)
```

**Comment by dashan1127** [comment]
Hello brother, I have another new question. The langchain/langgraphjs-api service has been started successfully (port is 8123:8000), and the ok interface is returned normally, but when I adjust the front end, I find that 404 is found. Is there something wrong with my opencanvas configuration?
![image](https://github.com/user-attachments/assets/13c11b3d-f455-4caf-b9f7-fe7765587c35)
![image](https://github.com/user-attachments/assets/c14acbe0-e96e-4b58-8290-5c1a63f856b8)
So, what should be configured for the hosts of these interfaces /api/threads/search /api/threads /api/assistants etc./api/*?

**Comment by lanesky** [comment]
@dashan1127  
Does the port match the `LANGGRAPH_API_URL` in `constants.ts`? You can also check the `Response` for any additional information.

**Comment by dashan1127** [comment]
Brother, I haven't worked on this recently, and started working on it again today. The front-end service can be started, but when I was doing Q&A, I got an error when I increased the model size. The log showed MODEL_NOT_FOUND. Can you help me figure out what's going on?


2024-11-28T13:28:41.233678Z [info     ] HTTP Request: POST http://graph/agent/streamEvents "HTTP/1.1 200 OK" [httpx] api_revision=4da016a api_variant=local
config.configurable!! {
  run_id: '1efad8ca-e6ac-6757-b402-a013bbb03ac5',
  user_id: '',
  graph_id: 'agent',
  thread_id: '7eb06ea8-c1ca-4a0a-b026-b7372cc2bf0c',
  assistant_id: 'b5b05dbe-5236-41f4-88c3-f5547380e62d',
  customModelName: 'gpt-4o',
  __pregel_resuming: false,
  __pregel_task_id: '989fad13-ef49-50a2-9470-01f11cffdee2',
  __pregel_send: [Function: __pregel_send],
  __pregel_read: [Function: __pregel_read],
  __pregel_checkpointer: RemoteCheckpointer { serde: JsonPlusSerializer {} },
  checkpoint_map: { '': '1efad8ca-ee0f-65e0-8000-dff544dbd5bf' },
  checkpoint_id: undefined,
  checkpoint_ns: 'generatePath:989fad13-ef49-50a2-9470-01f11cffdee2'
}
{"timestamp":"2024-11-28T13:28:41.878Z","level":"error","event":"Error: 404 status code (no body)\n\nTroubleshooting URL: https://js.langchain.com/docs/troubleshooting/errors/MODEL_NOT_FOUND/\n\n    at Function.generate (/deps/open-canvas/node_modules/openai/src/error.ts:82:14)\n    at OpenAI.makeStatusError (/deps/open-canvas/node_modules/openai/src/core.ts:435:21)\n    at OpenAI.makeRequest (/deps/open-canvas/node_modules/openai/src/core.ts:499:24)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///deps/open-canvas/node_modules/@langchain/openai/dist/chat_models.js:1553:29\n    at async RetryOperation._fn (/deps/open-canvas/node_modules/p-retry/index.js:50:12)","status":404,"headers":{"connection":"keep-alive","content-encoding":"gzip","content-type":"application/json;charset=utf-8","date":"Thu, 28 Nov 2024 13:28:41 GMT","keep-alive":"timeout=20","transfer-encoding":"chunked","vary":"accept-encoding"},"lc_error_code":"MODEL_NOT_FOUND","attemptNumber":1,"retriesLeft":6,"pregelTaskId":"989fad13-ef49-50a2-9470-01f11cffdee2","stack":"Error: 404 status code (no body)\n\nTroubleshooting URL: https://js.langchain.com/docs/troubleshooting/errors/MODEL_NOT_FOUND/\n\n    at Function.generate (/deps/open-canvas/node_modules/openai/src/error.ts:82:14)\n    at OpenAI.makeStatusError (/deps/open-canvas/node_modules/openai/src/core.ts:435:21)\n    at OpenAI.makeRequest (/deps/open-canvas/node_modules/openai/src/core.ts:499:24)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///deps/open-canvas/node_modules/@langchain/openai/dist/chat_models.js:1553:29\n    at async RetryOperation._fn (/deps/open-canvas/node_modules/p-retry/index.js:50:12)","message":"404 status code (no body)\n\nTroubleshooting URL: https://js.langchain.com/docs/troubleshooting/errors/MODEL_NOT_FOUND/\n"}

**Comment by dashan1127** [comment]
> Brother, I haven't worked on this recently, and started working on it again today. The front-end service can be started, but when I was doing Q&A, I got an error when I increased the model size. The log showed MODEL_NOT_FOUND. Can you help me figure out what's going on?
> 
> 2024-11-28T13:28:41.233678Z [info ] HTTP Request: POST http://graph/agent/streamEvents "HTTP/1.1 200 OK" [httpx] api_revision=4da016a api_variant=local config.configurable!! { run_id: '1efad8ca-e6ac-6757-b402-a013bbb03ac5', user_id: '', graph_id: 'agent', thread_id: '7eb06ea8-c1ca-4a0a-b026-b7372cc2bf0c', assistant_id: 'b5b05dbe-5236-41f4-88c3-f5547380e62d', customModelName: 'gpt-4o', __pregel_resuming: false, __pregel_task_id: '989fad13-ef49-50a2-9470-01f11cffdee2', __pregel_send: [Function: __pregel_send], __pregel_read: [Function: __pregel_read], __pregel_checkpointer: RemoteCheckpointer { serde: JsonPlusSerializer {} }, checkpoint_map: { '': '1efad8ca-ee0f-65e0-8000-dff544dbd5bf' }, checkpoint_id: undefined, checkpoint_ns: 'generatePath:989fad13-ef49-50a2-9470-01f11cffdee2' } {"timestamp":"2024-11-28T13:28:41.878Z","level":"error","event":"Error: 404 status code (no body)\n\nTroubleshooting URL: [https://js.langchain.com/docs/troubleshooting/errors/MODEL_NOT_FOUND/\n\n](https://js.langchain.com/docs/troubleshooting/errors/MODEL_NOT_FOUND/%5Cn%5Cn) at Function.generate (/deps/open-canvas/node_modules/openai/src/error.ts:82:14)\n at OpenAI.makeStatusError (/deps/open-canvas/node_modules/openai/src/core.ts:435:21)\n at OpenAI.makeRequest (/deps/open-canvas/node_modules/openai/src/core.ts:499:24)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async file:///deps/open-canvas/node_modules/@langchain/openai/dist/chat_models.js:1553:29\n at async RetryOperation._fn (/deps/open-canvas/node_modules/p-retry/index.js:50:12)","status":404,"headers":{"connection":"keep-alive","content-encoding":"gzip","content-type":"application/json;charset=utf-8","date":"Thu, 28 Nov 2024 13:28:41 GMT","keep-alive":"timeout=20","transfer-encoding":"chunked","vary":"accept-encoding"},"lc_error_code":"MODEL_NOT_FOUND","attemptNumber":1,"retriesLeft":6,"pregelTaskId":"989fad13-ef49-50a2-9470-01f11cffdee2","stack":"Error: 404 status code (no body)\n\nTroubleshooting URL: [https://js.langchain.com/docs/troubleshooting/errors/MODEL_NOT_FOUND/\n\n](https://js.langchain.com/docs/troubleshooting/errors/MODEL_NOT_FOUND/%5Cn%5Cn) at Function.generate (/deps/open-canvas/node_modules/openai/src/error.ts:82:14)\n at OpenAI.makeStatusError (/deps/open-canvas/node_modules/openai/src/core.ts:435:21)\n at OpenAI.makeRequest (/deps/open-canvas/node_modules/openai/src/core.ts:499:24)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async file:///deps/open-canvas/node_modules/@langchain/openai/dist/chat_models.js:1553:29\n at async RetryOperation._fn (/deps/open-canvas/node_modules/p-retry/index.js:50:12)","message":"404 status code (no body)\n\nTroubleshooting URL: [https://js.langchain.com/docs/troubleshooting/errors/MODEL_NOT_FOUND/\n"}](https://js.langchain.com/docs/troubleshooting/errors/MODEL_NOT_FOUND/%5Cn%22%7D)

Also, I'm using AZURE_MODELS and AZURE_KEY
