### ISSUE TITLE
Replace LangSmith with LangFuse

### ISSUE THREAD

**Issue by IsraelShok** [langchain-ai/open-canvas#198]
Hi, There is an option to replace the connection to LangSmith with LangFuse?

Thanks

**Comment by bracesproul** [comment]
Hey, this is not something we'd be looking to add to the main repo, however you're free to fork it and add it to your personal repo!

**Comment by IsraelShok** [comment]
But can I disconnect langsmith?
I can see that you create a Client that is in the package of lang chain.
There is a way to remove this creation?
It’s combined together and I’m trying to understand how the change can be made.

**Comment by bracesproul** [comment]
@IsraelShok yes you can! To prevent LangSmith from tracing, set `LANGCHAIN_TRACING_V2` to `"false"`

**Comment by IsraelShok** [comment]
And then I will not need the langchain api key? 
all I see it’s used for creating a user for langsmith.
So what I missing here?

**Comment by bracesproul** [comment]
@IsraelShok  If you set `LANGCHAIN_TRACING_V2` to `"false"` you can ignore all other LangChain API keys. You'll still need a LangSmith account to run it though since it runs on LangGraph Cloud. It requires logging in to run locally (free tier supported), and a Plus subscription to deploy to production.

**Comment by IsraelShok** [comment]
I run it on docker, it’s still runs on langgraph cloud?
I can’t expose it to the cloud, there is a way to solve it?

thanks a lot for your help!
