### ISSUE TITLE
Embedding Open Canvas in an overall LangGraph app

### ISSUE THREAD

**Issue by bedney** [langchain-ai/open-canvas#220]
So I apologize in advance as I'm still coming up to speed on LangGraph, but I'm curious if it is possible to embed Open Canvas in an overall LangGraph application. I'd like to share state between my app and Open Canvas. Would this be done as a subgraph?

Thanks!

**Comment by bracesproul** [comment]
Yeah, to use the Open Canvas graph inside another graph you can either add it as a subgraph, or if the main graph you want to add Open Canvas to does not immediately depend on the output from the Open Canvas graph, then you can just invoke it within a node like I do [here](https://github.com/langchain-ai/open-canvas/blob/main/src/agent/open-canvas/nodes/reflect.ts) as to not block the main graph from completing while the Open Canvas graph runs.

If you do it that way, you should be able to use that code with minimum modifications as long as the Open Canvas graph is deployed in the same LangGraph project as your other graphs. If not, you'll need to update the base URL to point to your other LangGraph deployment.

---

LangGraph graphs can be used as subgraphs inside any other graph as long as they share at least one state field. If they don't, you can still use them inside other graphs, but you'll have to manually invoke them (like the file I linked above does) since they don't share any state fields.
